name: Auto-generate blog post

on:
  schedule:
    - cron: '0 3 */2 * *'  # every 2 days at 03:00 UTC
  workflow_dispatch:

jobs:
  autopost:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps (none required)
        run: python -V

      - name: Generate post with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 scripts/auto_post.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore: auto-generate blog post"

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


